---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: poker-table-ui-service
  name: poker-table-ui-service
spec:
  ports:
  - name: 4000-80
    port: 4000
    protocol: TCP
    targetPort: 80
  selector:
    app: poker-table-ui
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: poker-table-api-service
  name: poker-table-api-service
spec:
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: poker-table-api
  type: NodePort
status:
  loadBalancer: {}

